### ISSUE TITLE
w2-pandas-project Mar Sánchez de Salas

### ISSUE THREAD

**Issue by Mar26sds** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#10]
https://github.com/Mar26sds/data-cleaning-pandas-Proyecto-Sharks-Mar-Sanchez-de-Salas

**Comment by Gobuub** [comment]
Un trabajo muy limpio Mar (valga la redundancia XDDD), el readme esta bien, la presentación muy bien también y el notebook con el proceso de limpieza muy bien estructurado y con una buena documentación. Buen trabajo.
