### ISSUE TITLE
SHARKs-ATTACK-DATASET_Berta

### ISSUE THREAD

**Issue by Vert-ix** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#11]

**Comment by Vert-ix** [comment]
https://github.com/Vert-ix/SHARKs-ATTACK-DATASET_Berta.git

**Comment by Gobuub** [comment]
Bien hecho Berta, has hecho un buen trabajo de limpieza, el readme está muy completo y la presentación visualmente está muy bien y los datos coinciden con los del resto de tu compis. Buen trabajo, sigue así.
