### ISSUE TITLE
Data-Cleaning-Pandas-Project {Carlos Basco}

### ISSUE THREAD

**Issue by Carlosbasco93** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#12]
https://github.com/Carlosbasco93/Data-Cleaning-Pandas-Project

**Comment by Gobuub** [comment]
Buen trabajo Carlos, un proceso de limpieza bastante exhaustivo, echo de menos alguna función para evitar repetir líneas de código, y el readme que es un poco escueto :P.
