### ISSUE TITLE
W2-pandas-project[YasminMoreno]

### ISSUE THREAD

**Issue by YasminMoreno** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#13]
https://github.com/YasminMoreno/Proyecto-Sharks-Attacks_clean.git

**Comment by Gobuub** [comment]
Muy buen trabajo Yasmine, como único pero sería el tema de repetir la misma línea de codigo para casos particulares, en ese caso lo mejor es encapsular en una función y hacer un apply a la columna o en un bucle, pero bueno poco a poco.
