### ISSUE TITLE
 w2-pandas-project {Antonio López-Alanís}

### ISSUE THREAD

**Issue by antlopal3rd** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#15]

**Comment by antlopal3rd** [comment]
https://github.com/antlopal3rd/pandas-cleaning-sharks

**Comment by Gobuub** [comment]
Hay muchas líneas repetidas con un cambio muy ligero en cada una de ellas, por lo que sería un caso susceptible de aplicar una función y evitar de esta forma escribir el mismo código 50 veces :P.
