### ISSUE TITLE
W2-pandas-project-solution[Lucia Correa]

### ISSUE THREAD

**Issue by AtomLu** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#16]
https://github.com/AtomLu/pandas-project.git
[Shark attacks - Lucia Gabriela Correa.pptx](https://github.com/Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project/files/9397923/Shark.attacks.-.Lucia.Gabriela.Correa.pptx)

**Comment by Gobuub** [comment]
Buen trabajo Lucia, el readme esta correcto, me has separado la parte de análisis de la parte de limpieza, todo hecho de forma muy limpia, sigue así.
