### ISSUE TITLE
w2-pandas-project{Miguel Mota}

### ISSUE THREAD

**Issue by Miguelmotacava** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#19]
https://1drv.ms/p/s!AsDuCA7Vd9Zjiyd7GYrvdGKG4_RT?e=ILb8U2

https://github.com/Miguelmotacava/w2-pandas-project-mmc-.git

**Comment by Gobuub** [comment]
Buen trabajo Miguel, como ya hablamos el tema de que repitas la misma línea simplemente cambiando un valor, sería para pensar como optimizar eso, por ejemplo con una función, y haces un apply a esa columna. Pero bueno poco a poco.
