### ISSUE TITLE
Pablo GR

### ISSUE THREAD

**Issue by PabloGR1** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#2]
https://github.com/PabloGR1/w2-Project---Clean

Repositorio con el proyecto de la W2 Pandas Project

**Comment by Gobuub** [comment]
Esta todo perfect Pablo, el repo bien estructurado, la presentación bien hecha y visualmente atractiva y el trabajo de limpieza también está correcto, como en todo siempre se puede mejorar pero para ser el primero no se puede pedir más. Buen trabajo.
