### ISSUE TITLE
Javi Canela

### ISSUE THREAD

**Issue by javiercanela3** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#20]
https://github.com/javiercanela3/data-cleaning-pandas.git

**Comment by Gobuub** [comment]
El trabajo está perfecto, quizás te calentaste un poco con la gráfica que querías montar, en este caso me centraría en mostrar si quieres por actividad y y zona del ataque, de hecho así a bote pronto no se me ocurre como hacer una tabla como la que propones en el notebook y que sea legible, ya que lo que importa de los gráficos es que sean legibles, no que aporten toda la información posible, porque a veces eso puede ser contraproducente. La presentación es mejorable :P, visualmente hablando. Buen trabajo Javier.
