### ISSUE TITLE
Alonso H 

### ISSUE THREAD

**Issue by aherreraitie** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#3]
https://github.com/aherreraitie/Proyecto-Semana-2-Pandas-Data-Cleaning-.git

Link del proyecto semana 2

**Comment by Gobuub** [comment]
Buen trabajo Alonso, me ha gustado que te hayas peleado ya con seaborn para los gráficos, el readme está correcto, la presentación está correcta, visualmente no es la más atractiva XDD, pero seguro que si hubieras presentado hubiese sido mejor, ya que le falta un poco explicación a los gráficos. Sigue así.
