### ISSUE TITLE
Proyecto Sharks Esperanza

### ISSUE THREAD

**Issue by ecamposgo** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#4]
https://github.com/ecamposgo/data-cleaning-pandas

**Comment by Gobuub** [comment]
Buen trabajo Esperanza, la presentación cortita y al pie, muestra los datos que quieres y visualmente está correcta. El proceso de limpieza ha sido bastante correcto también, me ha gustado que hayas creado tu archivo de funciones. Sigue así.
