### ISSUE TITLE
Proyecto Sharknado [Jaime Leoz]

### ISSUE THREAD

**Issue by JaimeLeoz** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#6]
Jaime Leoz -

**Comment by JaimeLeoz** [comment]
https://github.com/JaimeLeoz/proyecto1-sharks-

**Comment by JaimeLeoz** [comment]
https://github.com/JaimeLeoz/proyecto1-sharks-

**Comment by Gobuub** [comment]
El repo muy bien estructurado, el readme bastante completo y la presentación también bastante bien. En general un buen trabajo.
