### ISSUE TITLE
w2-pandas-project{DavidMC}

### ISSUE THREAD

**Issue by Davidmcii** [Ironhack-Data-Madrid-Agosto-2022/w2-pandas-project#8]
https://github.com/Davidmcii/DMC-w2-pandas-project

**Comment by Gobuub** [comment]
Buen trabajo David, el repo muy bien estructurado, la presentación está mas que correcta, y me ha gustado mucho la slide en la que muestras los valores únicos antes y después del proceso de limpieza :). A tope.
